SOURCE = 'https://www.culture.ru/'
RABBIT_HOST = 'rmq'
RABBIT_PORT = '5672'
RABBIT_QUEUE = 'events'

DB_DRIVER='mysql+pymysql'
DB_USER='testuser'
DB_PASS='testp@ss'
DB_HOST='db'
DB_PORT='3306'
DB_NAME='testdb'